spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa  # Default user for H2
    password: ""  # No password for H2 by default (empty string)
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update tables in dev
    show-sql: true  # Log SQL queries in the console (useful for debugging)

# Enable H2 console for development
spring.h2.console:
  enabled: true
  path: /h2-console  # H2 database UI is accessible at http://localhost:8080/h2-console

server:
  port: 8081