server:
  port: 8080

spring:
  application:
    name: SkillLink-Backend
  profiles:
    active: dev  # Default profile, can be overridden by environment or command line

skilllink:
  cors:
    allowed-origins: "http://localhost:5173"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

jwt:
  expiration: 3600000
  refresh-token:
    expiration: 604800000